// const arr: Array<string | number> = ["mango", "apple", 23, 45];
// const car1: string = 'Dodge';
// const car2: string = 'La farrari';
// const car3: string = 'Lambo';
const carsName = ["Dodge Challenger", "Hellcat", "La farrie"];
console.log(carsName);
// carsName.shift();
// console.log(carsName);
carsName.unshift("Mehran");
console.log(carsName);
carsName.shift();
console.log(carsName);
carsName.splice(0, 1);
console.log(carsName);
export {};
